---
- name: "Ensure ntp is installed"
  community.general.pkg5:
    name: "service/network/ntp"
    state: present

- name: "Ensure ntp.conf is rendered"
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/inet/ntp.conf
    owner: root
    group: sys
    mode: '0644'
  notify: "Restart ntp"

- name: "Ensure ntp is enabled"
  ansible.builtin.service:
    name: "svc:/network/ntp:default"
    state: started
    enabled: true
