---
namespace: iambryant

name: solaris

version: 1.0.0

readme: README.md

authors:
  - iambryant

description: This collection includes roles for automating common tasks in Solaris.

license:
  - MIT

license_file: 'LICENSE'

tags:
  - solaris
  - infrastructure

dependencies:
  community.general: ">=8.0.0"

repository: https://github.com/iambryant/ansible-collection-solaris

documentation: https://github.com/iambryant/ansible-collection-solaris

homepage: http://example.com

issues: https://github.com/iambryant/ansible-collection-solaris/issues

build_ignore: []
