---
ldm_allow_reboot: false

ldm_primary_cores: 2
ldm_primary_mem: 16

ldm_spconfig_name: "base-config"

ldm_vcc_name: "primary-vcc0"
ldm_vds_name: "primary-vds0"
ldm_vsw_name: "primary-vsw0"
ldm_vsw_lan: "net0"

ldm_guests: []
