---
- name: "Ensure firewall is installed"
  community.general.pkg5:
    name: "network/firewall"
    state: present

- name: "Ensure pf.conf has include for {{ firewall_conf_name }}"
  ansible.builtin.lineinfile:
    path: /etc/firewall/pf.conf
    line: 'include "/etc/firewall.d/{{ firewall_conf_name }}"'
    state: present
    validate: '/usr/sbin/pfctl -nf %s'
  notify: Refresh firewall

- name: "Ensure pf.conf.ansible is rendered"
  ansible.builtin.template:
    src: global.conf
    dest: "/etc/firewall.d/{{ firewall_conf_name }}"
    owner: root
    group: sys
    mode: '0644'
  notify: "Restart firewall"

- name: "Ensure firewall is enabled"
  ansible.builtin.service:
    name: "svc:/network/firewall:default"
    state: started
    enabled: true
