---
- name: "Ensure firewall is installed"
  community.general.pkg5:
    name: "{{ firewall_package }}"
    state: present

- name: "Ensure global.conf is rendered"
  ansible.builtin.template:
    src: global.conf
    dest: "{{ firewall_config_include_dir }}/{{ firewall_conf_name }}"
    owner: root
    group: sys
    mode: '0644'
  notify: "Restart firewall"

- name: "Ensure pf.conf has include for {{ firewall_conf_name }}"
  ansible.builtin.lineinfile:
    path: "{{ firewall_config_file }}"
    line: 'include "{{ firewall_config_include_dir }}/{{ firewall_conf_name }}"'
    state: present
  notify: "Restart firewall"

- name: "Ensure firewall is enabled"
  ansible.builtin.service:
    name: "svc:/network/firewall:default"
    state: started
    enabled: true
