---
- name: "Ensure Automated Installer ISO file is copied"
  ansible.builtin.copy:
    src: "{{ automated_installer_service.iso_file }}"
    dest: "/var/tmp/{{ automated_installer_service.iso_file | basename }}"
    owner: root
    group: sys
    mode: '0644'

- name: "Ensure Automated Installer UAR file is copied"
  ansible.builtin.copy:
    src: "{{ automated_installer_service.uar_file }}"
    dest: "/var/tmp/{{ automated_installer_service.uar_file | basename }}"
    owner: root
    group: sys
    mode: '0644'
  when: automated_installer_service.uar_file is defined

- name: "Check if Automated Installer service already exists"
  ansible.builtin.command: "installadm list -n {{ automated_installer_service.name }}"
  register: automated_installer_service_check
  failed_when: false
  changed_when: false

- name: "Ensure Automated Installer service is created"
  ansible.builtin.command: >
    installadm create-service
    -n {{ automated_installer_service.name }}
    -s /var/tmp/{{ automated_installer_service.iso_file | basename }}
    {% if automated_installer_service.uar_file is defined %}
    -i /var/tmp/{{ automated_installer_service.uar_file | basename }}
    {% endif %}
    -y
  when: automated_installer_service_check['rc'] != 0
  changed_when: true

- name: "Manage custom Automated Installer manifests"
  when: automated_installer_service.manifest is defined
  block:
    - name: "Get current manifest from installadm for '{{ automated_installer_service.name }}'"
      ansible.builtin.command: >
        installadm export -n {{ automated_installer_service.name }} -m default_manifest
      register: automated_installer_manifest_current
      failed_when: automated_installer_manifest_current.rc not in [0, 1]
      changed_when: false

    - name: "Ensure custom manifest is copied"
      ansible.builtin.copy:
        src: "{{ automated_installer_service.manifest }}"
        dest: "/var/tmp/{{ automated_installer_service.manifest | basename }}"
        owner: root
        group: sys
        mode: '0600'

    - name: "Ensure default manifest is added to '{{ automated_installer_service.name }}'"
      ansible.builtin.command: >
        installadm create-manifest
        -n {{ automated_installer_service.name }}
        -m default_manifest
        -f /var/tmp/{{ automated_installer_service.manifest | basename }}
        -d
      when: automated_installer_manifest_current['rc'] != 0
      changed_when: true

    - name: "Ensure default manifest is updated for '{{ automated_installer_service.name }}'"
      ansible.builtin.command: >
        installadm update-manifest
        -n {{ automated_installer_service.name }}
        -m default_manifest
        -f /var/tmp/{{ automated_installer_service.manifest | basename }}
      when:
        - automated_installer_manifest_current['rc'] == 0
        - ( automated_installer_manifest_current.stdout | checksum !=
            lookup('file', automated_installer_service.manifest) | checksum )

- name: "Manage custom Automated Installer profiles"
  when: automated_installer_service.profile is defined
  block:
    - name: "Get current profile from installadm for '{{ automated_installer_service.name }}'"
      ansible.builtin.command: >
        installadm export -n {{ automated_installer_service.name }} -p default_profile
      register: automated_installer_profile_current
      failed_when: automated_installer_profile_current.rc not in [0, 1]
      changed_when: false

    - name: "Ensure custom profile is copied"
      ansible.builtin.copy:
        src: "{{ automated_installer_service.profile }}"
        dest: "/var/tmp/{{ automated_installer_service.profile | basename }}"
        owner: root
        group: sys
        mode: '0600'

    - name: "Ensure default profile is added to '{{ automated_installer_service.name }}'"
      ansible.builtin.command: >
        installadm create-profile
        -n {{ automated_installer_service.name }}
        -p default_profile
        -f /var/tmp/{{ automated_installer_service.profile | basename }}
      when: automated_installer_profile_current['rc'] != 0
      changed_when: true

    - name: "Ensure default profile is updated for '{{ automated_installer_service.name }}'"
      ansible.builtin.command: >
        installadm update-profile
        -n {{ automated_installer_service.name }}
        -p default_profile
        -f /var/tmp/{{ automated_installer_service.profile | basename }}
      when:
        - automated_installer_profile_current['rc'] == 0
        - ( automated_installer_profile_current.stdout | checksum !=
            lookup('file', automated_installer_service.profile) | checksum )
