---
- name: "Ensure installadm is installed"
  community.general.pkg5:
    name: install/installadm
    state: present

- name: "Ensure dhcpd4.conf is rendered before creating services"
  ansible.builtin.template:
    src: dhcpd4.conf.j2
    dest: /etc/inet/dhcpd4.conf
    owner: root
    group: sys
    mode: '0644'
  notify: "Ensure dhcpd is restarted"

- name: "Process Automated Installer services"
  ansible.builtin.include_tasks: create_service.yml
  loop: "{{ automated_installer_services }}"
  loop_control:
    loop_var: automated_installer_service

- name: "Process Automated Installer clients"
  ansible.builtin.include_tasks: create_client.yml
  loop: "{{ automated_installer_clients }}"
  loop_control:
    loop_var: automated_installer_client
