---
- name: "Ensure the target system is SPARC (sun4v) architecture"
  ansible.builtin.fail:
    msg: "This role requires the SPARC sun4v architecture to function. Detected: {{ ansible_facts['architecture'] }}"
  when: ansible_facts['architecture'] != 'sun4v'

- name: "Ensure Logical Domains Manager/Oracle VM Server for SPARC is installed"
  community.general.pkg5:
    name:
      - system/ldoms
      - system/ldoms/ldomsmanager
    state: present

- name: "Get LDOM facts and configurations"
  block:
    - name: "Get current primary domain status"
      ansible.builtin.command: "ldm list-domain -o status primary"
      register: ldm_current_status
      changed_when: false

    - name: "Get current primary domain configuration"
      ansible.builtin.command: "ldm list -p primary"
      register: ldm_current_config
      changed_when: false

    - name: "Get current SP configurations"
      ansible.builtin.command: "ldm list-spconfig"
      register: ldm_current_spconfig
      changed_when: false

    - name: "Get current primary domain services"
      ansible.builtin.command: "ldm list-services -p primary"
      register: ldm_current_services
      changed_when: false

    - name: "Ensure primary domain details are set as facts"
      ansible.builtin.set_fact:
        ldm_status_output: "{{ ldm_current_status.stdout }}"
        ldm_config_output: "{{ ldm_current_config.stdout }}"
        ldm_spconfigs: "{{ ldm_current_spconfig.stdout }}"
        ldm_services: "{{ ldm_current_services.stdout }}"

    - name: "Get currently assigned CPU cores and RAM for primary domain"
      ansible.builtin.set_fact:
        ldm_current_cores: >
          {{ ((ldm_current_config.stdout | regex_search('ncpu=[0-9]+')).split('=')[1] | int / 8) | int }}
        ldm_current_mem: >
          {{ ((ldm_current_config.stdout | regex_search('mem=[0-9]+')).split('=')[1] | int / 1024**3) | int }}

- name: "Ensure LDOM services are present"
  block:
    - name: "Ensure Virtual Console Concentrator (VCC) service is present"
      ansible.builtin.command: "ldm add-vcc port-range=5000-5100 {{ ldm_vcc_name }} primary"
      changed_when: true
      when: "ldm_vcc_name not in ldm_services"
      register: ldm_vcc_reg

    - name: "Ensure Virtual Disk Server (VDS) service is present"
      ansible.builtin.command: "ldm add-vds {{ ldm_vds_name }} primary"
      changed_when: true
      when: "ldm_vds_name not in ldm_services"
      register: ldm_vds_reg

    - name: "Ensure Virtual Switch (VSW) service is present"
      ansible.builtin.command: "ldm add-vsw net-dev={{ ldm_vsw_lan }} {{ ldm_vsw_name }} primary"
      changed_when: true
      when: "ldm_vsw_name not in ldm_services"
      register: ldm_vsw_reg

- name: "Ensure primary/control domain is configured"
  when:
    - "ldm_current_cores != (ldm_primary_cores | int) or ldm_current_mem != (ldm_primary_mem | int)"
    - "'delayed' not in ldm_status_output"
  block:
    - name: "Start delayed reconfiguration mode"
      ansible.builtin.command: "ldm start-reconf primary"
      changed_when: true

    - name: "Ensure CPU cores are assigned to primary domain"
      ansible.builtin.command: "ldm set-core {{ ldm_primary_cores }} primary"
      changed_when: true
      when: "ldm_current_cores != (ldm_primary_cores | int)"
      register: ldm_cores_reg

    - name: "Ensure RAM is assigned to primary domain"
      ansible.builtin.command: "ldm set-memory {{ ldm_primary_mem }}G primary"
      changed_when: true
      when: "ldm_current_mem != (ldm_primary_mem | int)"
      register: ldm_mem_reg

- name: "Ensure the virtual network terminal server daemon (vntsd) is enabled"
  ansible.builtin.service:
    name: "svc:/ldoms/vntsd:default"
    state: started
    enabled: true

- name: "Rebuild SP config if changes were made"
  when: >
    (ldm_vcc_reg is changed) or
    (ldm_vds_reg is changed) or
    (ldm_vsw_reg is changed) or
    (ldm_cores_reg is changed) or
    (ldm_mem_reg is changed)
  block:
    - name: "Remove existing SP configuration if it exists"
      ansible.builtin.command: "ldm remove-spconfig {{ ldm_spconfig_name }}"
      changed_when: true
      when: "ldm_spconfig_name in ldm_spconfigs"

    - name: "Ensure new SP configuration is added"
      ansible.builtin.command: "ldm add-spconfig {{ ldm_spconfig_name }}"
      changed_when: true

- name: "Handle system reboot to apply changes"
  when: "ldm_allow_reboot | bool"
  block:
    - name: "Check if primary domain needs to be rebooted"
      ansible.builtin.command: "ldm list-domain -o status primary"
      register: ldm_reboot_check
      changed_when: false

    - name: "Ensure primary domain is rebooted to apply SP configuration"
      ansible.builtin.reboot:
        reboot_timeout: 900
      when: "'delayed' in ldm_reboot_check.stdout"

# If running iambryant.solaris.ldom immediately after, this prevents errors from binding an guest LDOM immediately
# after system startup
- name: "Pause for 30 seconds to allow ldmd to initialize"
  ansible.builtin.pause:
    seconds: 30
